# LambdaTest Configuration

# Project and folder configuration
project_id: "01KJD631VY3SYENJXNKNVDFCCK"
folder_id: "01KJD632TDM2AD6DJQMCT41CPT"

# Test Run configuration
assignee: 2122043
environment_id: 2

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
